# Generated by Django 3.2.12 on 2022-02-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('static_map', models.ImageField(blank=True, null=True, upload_to='imgs')),
                ('speed', models.IntegerField(null=True)),
                ('average_speed', models.IntegerField(null=True)),
                ('Temprature', models.IntegerField(null=True)),
                ('Fuel_level', models.IntegerField(null=True)),
                ('Engine_status', models.BooleanField(default=False)),
            ],
        ),
    ]
